--require("LuaPanda").start("127.0.0.1",8818)
--package.cpath = package.cpath .. ';C:/Users/heziqi/AppData/Roaming/JetBrains/Rider2022.3/plugins/EmmyLua/debugger/emmy/windows/x64/?.dll'
--local dbg = require('emmy_core')
--dbg.tcpConnect('localhost', 8818)
--dbg.waitIDE()
